name: LaTeX Compile & Spellcheck

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: set date env
        run: echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      - name: Lint LaTeX document
        uses: ChiefGokhlayeh/textidote-action@v5
        id: lint
        with:
          root_file: main.tex
          args: --check en --dict en_US.dict
      - uses: xu-cheng/latex-action@v3
        name: Github Action for LaTeX
        with:
          root_file: main.tex
      - name: Convert LaTeX to HTML
        run: |
          sudo apt-get update
          sudo apt-get install -y make latexmk zip ghostscript dvisvgm
          curl -L -o latexml.tar.gz https://github.com/brucemiller/LaTeXML/archive/v0.8.6.tar.gz
          tar -xzf latexml.tar.gz
          cd LaTeXML-0.8.6
          perl Makefile.PL
          make
          sudo make install
          cd ..
          git clone https://github.com/LeedsUni/BookML.git
          cp -r BookML/bookml .
          cp BookML/GNUmakefile .
          make
      - name: Throw error if linter warnings exist
        if: ${{ steps.lint.outputs.num_warnings != 0 }}
        run: 'echo "::error file=main.tex::num_warnings: ${{ steps.lint.outputs.num_warnings }}";'
      - name: Upload completed PDF
        uses: actions/upload-artifact@v4
        with:
          name: final-report-v${{ github.run_number }}-${{ env.NOW }}.pdf
          path: main.pdf
      - name: Upload TeXtidote report
        uses: actions/upload-artifact@v4
        with:
          name: textidote-report-v${{ github.run_number }}-${{ env.NOW }}.html
          path: report.html
      - name: Upload report HTML
        uses: actions/upload-artifact@v4
        with:
          name: final-report-v${{ github.run_number }}-${{ env.NOW }}.html
          path: main.html
      - name: Rename textidote report
        run: mv report.html textidote-report.html
      - name: Rename latex report
        run: mv main.pdf final-report-v${{ github.run_number }}-${{ env.NOW }}.pdf
      - name: Rename HTML report
        run: mv main.html final-report-v${{ github.run_number }}-${{ env.NOW }}.html
      - name: Tag the repository
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Action"
          git config user.email "bloop@blorp.com"
          git tag -a v${{ github.run_number }}-${{ env.NOW }} -m "Published version v${{ github.run_number }}"
          git push origin v${{ github.run_number }}-${{ env.NOW }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_number }}-${{ env.NOW }}
          files: |
            textidote-report.html
            final-report-v${{ github.run_number }}-${{ env.NOW }}.pdf
            final-report-v${{ github.run_number }}-${{ env.NOW }}.html
